<a href="https://colab.research.google.com/github/park1125/Curating_Code/blob/master/3_%EB%B6%93%EA%BD%83%ED%92%88%EC%A2%85%EC%98%88%EC%B8%A1%ED%95%98%EA%B8%B0_%EB%B0%B0%ED%8F%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# scikit-learn 설치
# pip install scikit-learn

In [ ]:
# scikit-learn import

import sklearn
print(sklearn.__version__)

0.22.2.post1


## Q1. 붓꽃 품종 예측하기
- 붓꽃 데이터 셋트로 붓꽃의 품종을 분류(Classification)하기
- https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_iris.html?highlight=iris#sklearn.datasets.load_iris

![img02-iris.png](http://drive.google.com/uc?export=view&id=1wRDNj7hsZH-niTbcYePPwSTsDKBqohYl)


In [ ]:
# sklearn.datasets : 사이킷런에서 제공하는 테스트 데이터셋의 모음
# sklearn.tree : 트리 기반 ML 알고리즘을 구현한 클래스의 모음
# sklearn.model_selection : 


from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split 



#### step1. 붓꽃 데이터 로딩

In [ ]:
iris = load_iris()
iris.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [ ]:
# data 살펴보기
print(type(iris.data))

iris_data = iris.data
print(iris_data.shape)   # (150,4) ==> 4개의 열(feature)를 가진 150개 행
print(iris_data[:5])
print(iris.feature_names)

<class 'numpy.ndarray'>
(150, 4)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [ ]:
# target 살펴보기
# target, label, 레이블, 라벨, 정답 -> 몇 개의 class

print(iris.target)

iris_label = iris.target   # iris_label 에 copy
print(iris_label.shape)    # (150,)
print(iris.target_names)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
(150,)
['setosa' 'versicolor' 'virginica']


In [ ]:
# dataframe 으로 변환
import pandas as pd

# iris_data (4 col) + iris_label (1 col)
df_iris = pd.DataFrame(data=iris_data, columns=iris.feature_names)
# df_iris['label'] 추가하겠습니다.
df_iris['label'] = iris_label
df_iris.head()

df_iris[95:105]

sepal length (cm)  sepal width (cm)  ...  petal width (cm)  label
95                 5.7               3.0  ...               1.2      1
96                 5.7               2.9  ...               1.3      1
97                 6.2               2.9  ...               1.3      1
98                 5.1               2.5  ...               1.1      1
99                 5.7               2.8  ...               1.3      1
100                6.3               3.3  ...               2.5      2
101                5.8               2.7  ...               1.9      2
102                7.1               3.0  ...               2.1      2
103                6.3               2.9  ...               1.8      2
104                6.5               3.0  ...               2.2      2

[10 rows x 5 columns]

#### step 2. 데이터세트 분리
- 데이터를 학습(train) 데이터와 테스트(test) 데이터로 분리
- train_test_split() : test_size=0.2 (테스트 20% = 30건 , 학습 80% = 120건 분할)

In [ ]:
x_train, x_test, y_train, y_test  = train_test_split(iris_data, 
                                                     iris_label , 
                                                     test_size= 0.2, 
                                                     random_state=11 )

# y =f(x)  x : feature들  , y : label

In [ ]:
print(x_train.shape)    # (120 , 4 ) 
print(y_train.shape)    # (120 , )
print(x_test.shape)     # (30 , 4)
print(y_test.shape)     # (30  , )
# train = 학습용,  test : 검증용

(120, 4)
(120,)
(30, 4)
(30,)


In [ ]:
y_train

array([0, 2, 2, 0, 0, 2, 2, 1, 0, 1, 1, 2, 0, 1, 2, 1, 1, 0, 2, 0, 2, 2,
       1, 2, 1, 0, 0, 1, 0, 0, 2, 2, 2, 0, 0, 0, 1, 0, 1, 2, 2, 1, 1, 2,
       2, 0, 1, 1, 2, 2, 2, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 1, 0, 1, 1, 2,
       1, 0, 0, 0, 1, 1, 1, 2, 1, 0, 1, 2, 0, 2, 2, 1, 0, 0, 0, 2, 1, 0,
       2, 1, 2, 0, 0, 1, 1, 2, 1, 2, 2, 1, 1, 2, 2, 0, 1, 2, 0, 2, 2, 0,
       1, 2, 0, 1, 1, 1, 0, 1, 1, 1])

#### step 3. DecisionTreeClassifier 객체 생성
- 모델을 생성

In [ ]:
dt_clf = DecisionTreeClassifier(random_state=11)

#### step 4. 모델 학습
- 학습데이터를 기반으로 ML 알고리즘을 적용해 모델을 학습시킴

In [ ]:
dt_clf.fit( x_train , y_train )   # 지도학습 120건

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=11, splitter='best')

#### step 5. 예측 수행
- 학습된 ML모델을 이용해 테스트 데이터의 분류(즉, 붓꽃 종류)를 예측
- 학습이 완료된 DecisionTreeClassifier 객체에서 테스트 데이터 세트로 예측 수행

In [ ]:
pred = dt_clf.predict(x_test)   # 30건 

In [ ]:
pred

array([2, 2, 1, 1, 2, 0, 1, 0, 0, 1, 1, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0,
       0, 1, 0, 0, 2, 1, 0, 1])

In [ ]:
y_test

array([2, 2, 2, 1, 2, 0, 1, 0, 0, 1, 2, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0,
       0, 1, 0, 0, 2, 1, 0, 1])

In [ ]:
# 30건 2개 오차 
# accuracy =  맞춘건수 /전체건수
28/30 
# 0.9333333333333333

0.9333333333333333

#### step 6. 평가
- 이렇게 예측된 결괏값과 테스트 데이터의 실제 결괏값을 비교해 ML 모델 성능을 평가

In [ ]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test, pred)

0.9333333333333333

## Q2. 사이킷런 프레임워크 익히기
- Estimator 이해 및 fit(), predict() 메서드
- 기본 Estimator 클래스 : 분류와 회귀로 나눔


<img src="http://drive.google.com/uc?export=view&id=19SSruDuzqIh2pICZiM9RhPbbvxoVXNTM" width="600">

- 사이킷런의 주요 모듈 
- https://scikit-learn.org/stable/modules/classes.html

<img src="http://drive.google.com/uc?export=view&id=1KACaXAKgxwLw_QlbM7kh6kTuywJqzEbs" width="900">

## Q3. 내장된 예제 데이터 세트 - 분류나 회귀용
- 예제 데이터의 구성 
- https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_iris.html?highlight=iris#sklearn.datasets.load_iris
- 일반적으로 딕서너리 형태로 되어 있음
- 키는 data, target, target_names, feature_names, DESCR


In [ ]:
# sklearn.utils.Bunch 는 파이썬의 딕셔너리와 비슷






## Q4. Model Selection 모듈 소개
- 데이터 세트 분리
- 교차 검증 분할 및 평가
- Estimator의 하이퍼 파라미터 튜닝을 위한 다양한 함수와 클래스 제공

### 1) train/test 데이터 세트 분리 - train_test_split()
- train/test 데이터 세트 분리 이유
- test 데이터를 이용하기 않고 train 데이터 세트만으로 학습하고 예측해보자

In [ ]:
iris = load_iris()
dt_clf = DecisionTreeClassifier()
train_data = iris.data
train_label = iris.target

dt_clf.fit(train_data, train_label)  

# 학습 데이터 세트로 예측 수행
pred = dt_clf.predict(train_data)  
print(accuracy_score(train_label, pred))


1.0


- train_test_split()
- test_size : 전체 데이터에서 테스트 데이터 세트의 크기를 얼마로 샘플링할 것인가를 결정, default 0.25
- train_size : 전체 데이터에서 학습용 데이터 세트의 크기를 얼마로 샘플링할 것인가를 결정, 통상적으로 test_size 사용
- shuffle : 데이타를 분리하기 전에 미리 섞을지를 결정, default True
- random_state : 무작위로 데이터를 분리하므로 random_state를 지정하지 않으면 수행할 때마다 다른 train/test 데이터세트를 생성, 
random값을 만드는 seed와 같은 의미

### 2) 교차 검증
- KFold, Stratified KFold, cross_val_score() 
- Overfitting : 모델이 학습 데이터에만 과도하게 최적화되어, 실제 예측을 다른 데이터로 수행할 경우에는 예측 성능이 과도하게 떨어지는 것을 의미
- 본고사 치르지 건에 모의고사를 여러번 보는 것과 같음
- 학습 데이터를 다시 분할하여 학습 데이터와 학습된 모델의 성능을 일차 평가하는 검증 데이터로 나눔
- 검증 데이터세트로 1차 평가를 한 뒤에 최종적으로 테스트 데이터세트에 적용해 평가하는 프로세스
- train/validation/test dataset

#### 2-1) K 폴드 교차 검증
- K 개의 폴드를 만들어서 진행하는 교차검증

[과정]

- Training set과 Test set을 나눈다
- Training set을 K개의 fold로 나눈다 
- 한 개의 fold에 있는 데이터를 다시 K개로 쪼갠 다음, K-1개는 Training data, 마지막 한개는 Validation data로 지정한다
- Training data로 학습을 수행하고 Validation data로 평가를 수행한다 
- 두번째 반복에서 Training data와 Validation data를 변경하여 같은 방식으로 학습과 평가 작업을 수행한다
- 이런식으로 데이터 셋을 점진적으로 변경하면서 K번째까기 학슴과 검증을 수행한다
- K개의 예측 평가를 구했으면 이를 평균해서 K폴드 평가 결과로 반영한다

<img src="http://drive.google.com/uc?export=view&id=1JDNpCIDhJdw7slx5fCY12Q827jaKHDnE" width="600">

[사용이유]

- 총 데이터 개수가 적은 데이터 세트에 대해 정확도를 향상시킬 수 있음
- 이는 train/validation/test dataset으로 분류하는 것이 training과 test로만 분류할 때보다 학습 데이터셋이 더 많기 때문
- 데이터 수가 적으면 과소적합



- K폴드 교차 검증 구현


In [ ]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split , KFold
from sklearn.metrics import accuracy_score
import numpy as np

# iris load
iris = load_iris()
features = iris.data
label = iris.target

# train_test_split  생략  전체 150건
# classifier 객체 생성
dt_clf = DecisionTreeClassifier(random_state=156)

# kfold 객체 생성
kfold = KFold(n_splits=5)
cv_accuracy = []   # cv = cross validtaion 

for train_index , test_index in kfold.split(features) : # k 갯수만큼 for문 반복
    # train, test 셋 만들고
    x_train = features[train_index]
    x_test  = features[test_index] 
    y_train = label[train_index]
    y_test  = label[test_index]

    # fit, predict , score -> list 담기 
    dt_clf.fit(x_train, y_train)
    pred = dt_clf.predict(x_test)
    accuracy = accuracy_score(y_test, pred)

    cv_accuracy.append(accuracy)

from sklearn.metrics import accuracy_score <- 위에 이거 추가해주세요
import numpy as np <- 위에 추가해주세요
# list에 있는 accuracy를 평균
print(cv_accuracy)   # 5개
print(np.mean(cv_accuracy))


[1.0, 0.9666666666666667, 0.8666666666666667, 0.9333333333333333, 0.7333333333333333]
0.9


- K폴드 교차검증의 함정

In [ ]:
print(test_index)

[120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]


In [ ]:
print(label)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


#### 2-2) Stratified K 폴드 
- 원본 데이터의 레이블 분포를 먼저 고려한 뒤 이 분포와 동일하게 분배하는 방식
- 왜곡된 레이블 데이터 세트에서는 반드시 Stratified K폴드를 이용해 교차 검증을 해야함
- 분류에서의 교차 검증은 Stratified K폴드로 분할
- 회귀에서는 Stratified K폴드 지원하지 않음 ( 회귀의 결정값은 이산값이 아니라 연속된 숫자값이기 때문에 결정값별로 분포를 정하는 게 의미없음)

In [ ]:
# Stratified K 폴드 구현



1번째 교차검증 정확도 : 0.9667, 학습데이터 크기 : 120, 검증데이터 크기 : 30
1번째 검증 세트 인덱스 : [  0   1   2   3   4   5   6   7   8   9  50  51  52  53  54  55  56  57
  58  59 100 101 102 103 104 105 106 107 108 109]

2번째 교차검증 정확도 : 0.9667, 학습데이터 크기 : 120, 검증데이터 크기 : 30
2번째 검증 세트 인덱스 : [ 10  11  12  13  14  15  16  17  18  19  60  61  62  63  64  65  66  67
  68  69 110 111 112 113 114 115 116 117 118 119]

3번째 교차검증 정확도 : 0.9, 학습데이터 크기 : 120, 검증데이터 크기 : 30
3번째 검증 세트 인덱스 : [ 20  21  22  23  24  25  26  27  28  29  70  71  72  73  74  75  76  77
  78  79 120 121 122 123 124 125 126 127 128 129]

4번째 교차검증 정확도 : 0.9667, 학습데이터 크기 : 120, 검증데이터 크기 : 30
4번째 검증 세트 인덱스 : [ 30  31  32  33  34  35  36  37  38  39  80  81  82  83  84  85  86  87
  88  89 130 131 132 133 134 135 136 137 138 139]

5번째 교차검증 정확도 : 1.0, 학습데이터 크기 : 120, 검증데이터 크기 : 30
5번째 검증 세트 인덱스 : [ 40  41  42  43  44  45  46  47  48  49  90  91  92  93  94  95  96  97
  98  99 140 141 142 143 144 145 146 147 148 149]

교차 검증별 정확도 : [0.9667 0.9667 0.9    0.9667

#### 2-3) 교차 검증을 보다 간편하게 - cross_val_score()
- 교차 검증을 위한 API 제공
- 일련의 과정을 한꺼번에 수행해주는 API - cross_val_score()
- https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.cross_val_score.html
- cross_val_score(estimator, X, y=None, *, groups=None, scoring=None, cv=None, n_jobs=None, verbose=0, fit_params=None, pre_dispatch='2*n_jobs', error_score=nan)
- estimator : 분류 알고리즘 클래스
- X : 피처 데이터 세트
- y : 레이블 데이터 세트
- scoring : 예측 성능 평가 지표 ( 예. scoring='accuracy' )
- cv : 교차 검증 플드 수
- 반환값 : 성능 지표 측정값을 배열 형태로 반환

In [ ]:
from sklearn.model_selection import cross_val_score

# load
iris = load_iris()
features = iris.data
label = iris.target

# dt_clf 생성
dt_clf = DecisionTreeClassifier(random_state=10)

# kfold-> for 문 (fit predict score)  ==> cross_val_score
scores = cross_val_score ( dt_clf, features, label, scoring='accuracy', cv=5)
print(scores)
print(np.mean(scores))

[0.96666667 0.96666667 0.9        0.93333333 1.        ]
0.9533333333333334


### 3) GridSearchCV - 교차 검증과 최적 하이퍼 파라미터 튜닝을 한 번에
- 하이퍼 파라미터란? 모델에서 외적인 요소 즉 데이터 분석을 통해 얻어지는 값이 아님
- GridSearchCV API는 분류나 회귀와 같은 알고리즘에 사용되는 하이퍼 파라미터를 순차적으로 입력하며서 편리하게 최적의 파라미터를 도출할 수 있는 방안을 제공 (Grid란 격자라는 뜻으로 촘촘하게 파라미터를 입력하면서 테스트를 하는 방식)


[ 하이퍼 파라미터 특징 ]

- 모델 파라미터 값을 측정하기 위해 알고리즘 구현 과정에서 사용된다
- 주로 알고리즘 사용자에 의해 결정된다
- 경험에 의해 정해지기도 한다. 즉 알고리즘을 여러 번 수행해보면서 최적의 값을 직감적으로 알게된다
- 예측 알고리즘 모델링의 문제점을 위해 조절된다
- 예) 딥러닝에서 learning rate, 분류에서 max_depth, KNN에서 K의 개수


In [ ]:
# import 
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split, GridSearchCV # 추가
from sklearn.metrics import accuracy_score

# load 
iris = load_iris()
iris_data = iris.data
iris_label = iris.target

# train_test_split 
x_train, x_test, y_train, y_test  = train_test_split(iris_data, 
                                                     iris_label , 
                                                     test_size= 0.2, 
                                                     random_state=11 )

# dt_clf 객체 생성
dt_clf = DecisionTreeClassifier(random_state=11)

# parameter 만들고 ~
parameters = {'max_depth':[1,2,3], 'min_samples_split':[2,3]}  # 6개 case 
grid_tree = GridSearchCV(dt_clf, param_grid=parameters, cv=3, refit=True) # 6*cv = 18번
grid_tree.fit(x_train, y_train)

In [ ]:
import pandas as pd 
df = pd.DataFrame(grid_tree.cv_results_)

In [ ]:
df[['params','mean_test_score','rank_test_score' ]]

params  mean_test_score  rank_test_score
0  {'max_depth': 1, 'min_samples_split': 2}         0.675000                5
1  {'max_depth': 1, 'min_samples_split': 3}         0.675000                5
2  {'max_depth': 2, 'min_samples_split': 2}         0.958333                3
3  {'max_depth': 2, 'min_samples_split': 3}         0.958333                3
4  {'max_depth': 3, 'min_samples_split': 2}         0.966667                1
5  {'max_depth': 3, 'min_samples_split': 3}         0.966667                1

In [ ]:
grid_tree.best_params_

{'max_depth': 3, 'min_samples_split': 2}

In [ ]:
grid_tree.best_score_   # 3% train data에 과대적합 최적화

0.9666666666666667

In [ ]:
est = grid_tree.best_estimator_   # 
pred = est.predict(x_test)
accuracy_score(y_test, pred)   # 일반화 모델 

0.9333333333333333

## Q5. 데이터 전처리
- Garbage In, Garbage Out
- 결손값(NaN, Null) : 허용 안됨, 고정된 다른 값으로 변환, 대부분이라면 삭제, 중요도가 높은 피처의 경우 정밀한 대체 값을 선정.
- 문자열 값: 허용 안됨. 숫자형으로 변환. 카테고리형 피쳐는 코드 값으로, 텍스트형 피처는 피처 백터화, 불필요한 피처는 삭제

### 1) 데이터 인코딩
- 인코딩이란 ? 정보의 형태나 형식을 변환하는 처리나 처리 방식, 부호화
- 인코딩 방식 : 레이블 인코딩 ( label encoding ), 원-핫 인코딩 (One Hot encoding)

#### 1-1 레이블 인코딩
- 카테고리 피처를 코드형 숫자 값으로 변환하는 것
- LabelEncoder 클래스로 구현
- LabelEncoder 객체 생성 후 fit(), transform() 

In [ ]:
from sklearn.preprocessing import LabelEncoder

items = ['TV', '냉장고', '컴퓨터', '믹서', '컴퓨터', '선풍기']

# 객체생성 -> fit -> transform
encoder = LabelEncoder()
encoder.fit(items)   # 기준정보 설정, 학습 x
labels = encoder.transform(items)  # 변환

print(labels)

[0 1 4 2 4 3]


In [ ]:
# 숫자값에 대한 class 이름 정보
encoder.classes_

array(['TV', '냉장고', '믹서', '선풍기', '컴퓨터'], dtype='<U3')

In [ ]:
# 디코딩
encoder.inverse_transform([3,4])

array(['선풍기', '컴퓨터'], dtype='<U3')

#### 1-2 원-핫 인코딩 (One-Hot Encoding)
- label encoding이 일괄적인 숫자 값으로 변환하는데 숫자 값의 크고 작음에 대한 특성이 작용해 예측 성능이 떨어지는 경우 발생
- 1보다 2가 더 큰 값이므로 특정 ML 알고리즘에서 가중치가 더 부여되거나 더 중요하게 인식할 가능성 발생
- 따라서 레이블 인코딩은 선형회귀에서는 적용 X, 트리 계열 알고리즘은 숫자의 이러한 특성을 반영하지 않음
- 이 문제점을 해결하기 위해 원-핫 인코딩 방식 
- 원-핫 인코딩 : 
- OneHotEncoder 클래스로 구현

In [ ]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

items = ['TV', '냉장고', '컴퓨터', '믹서', '컴퓨터', '선풍기']

# label encoding 객체생성 -> fit -> transform
encoder = LabelEncoder()
encoder.fit(items)   # 기준정보 설정, 학습 x
labels = encoder.transform(items)  # 변환

labels = labels.reshape(-1,1)  # 2D로 변환

# one hot encoding 객체생성 -> fit -> transform
ohencoder = OneHotEncoder()
ohencoder.fit(labels)   # 2D 
ohlabels = ohencoder.transform(labels)

print(type(ohlabels))
print(ohlabels.toarray())

<class 'scipy.sparse.csr.csr_matrix'>
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]]


### 2) 피처 스케일링과 정규화
- 서로 다른 변수의 값 범위를 일정한 수준으로 맞추는 작업을 피처 스케일링이라고 합니다
- 예. 달러와 원화를 비교하기 위해 가격의 단위를 조정 
- 대표적인 방법으로 표준화(StandardScaler) 와 정규화(Normalization)이 있습니다
- 데이터 특징에 따라서 선택

#### 2-1 표준화 - StandardScaler
- 표준화는 데이터의 피처 각각이 평균이 0이고 분산이 1인 가우시안 정규 분포를 가진 값으로 변환하는 것을 의미
- 표준화를 쉽게 지원하는 클래스 StandardScaler
- SVM, 선형 회귀, 로지스틱 회귀는 데이터가 가우시안 분포를 가지고 있다고 가정하고 구현됐기 때문에 사전에 표준화를 적용하는 것은 예측 성능 향상에 중요한 요소가 됩니다

<img src="http://drive.google.com/uc?export=view&id=1si8GD9t3rsMmKEBzDmp2wTBM9vkcVSAa" width="600">

In [ ]:
from sklearn.preprocessing import StandardScaler

iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)

print ("****************")
print (iris_df.mean())
print (iris_df.var())

scaler = StandardScaler()

scaler.fit(iris_df)
t_scaler = scaler.transform(iris_df)
print(iris_df.shape)

iris_df = pd.DataFrame(data=t_scaler, columns=iris.feature_names) 
print ("****************")
print (iris_df.mean())
print (iris_df.var())


****************
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64
(150, 4)
****************
sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


#### 2-2 MinMaxScaler
- 정규화란 개별 데이터의 크기를 모두 똑같은 단위로 변경하는 것
- 데이터 값을 0과 1사이의 범위 값으로 변환
- 정규화를 지원하는 클래스 MinMaxScaler
- 데이터 분포가 가우시안 분포가 아닐 경우 적용해 볼 수 있음

<img src="http://drive.google.com/uc?export=view&id=1ON54xIjh7-iALWJXd-HIhHzq611_E5Jo" width="250">

In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)
print(iris_df_scaled.min())
print(iris_df_scaled.max())

sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64


#### 2-3 스케일링 변환 시 유의점
- fit(), transform(), fit_transform()
- fit()은 데이터 변환을 위한 기준 정보 설정 (예를 들어 데이터세트의 최댓값/최솟값 설정)
- transform() 은 이 정보를 이용해 데이터를 변환
- 주의점. 학습 데이터로 fit()이 적용된 스케일링 기준 정보를 그대로 테스트 데이터에 적용해야함. 
- 즉, Scaler 객체를 이용해 학습 데이터 세트로 fit()과 transform()을 적용하면 테스트 데이터로는 다시 fit()을 수행하지 않고 fit()한 결과를 이용해 transform()변환을 적용해야 함 

[스케일링 변환 시 유의 점 요약]

1. 가능하다면 전체 데이터의 스케일링 변환을 적용한 뒤 학습과 테스트 데이터로 분리
2. 1이 여의치 않다면 테스트 데이터 변환 시에는 fit()이나 fit_transform()을 적용하지 않고 학습 데이터로 이미 fit()된 Scaler 객체를 이용해 transform()으로 변환